name: fresh_builder
description: Cross-platform FreshSTL Builder client.
publish_to: "none"
version: 0.3.0+3

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.13.0
  supabase_flutter: ^2.10.3
  http: ^1.5.0
  path_provider: ^2.1.5
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
