name: fresh_builder
description: Cross-platform FreshSTL Builder client.
publish_to: "none"
version: 0.4.0+4

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.13.0
  flutter_rust_bridge_hooks: 2.13.0
  fresh_builder_viewport_texture:
    path: packages/fresh_builder_viewport_texture
  supabase_flutter: 2.18.0
  http: 1.5.0
  path_provider: 2.1.5
  crypto: 3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
